// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MetalDetector from "./MetalDetector.bs.js";

function App(Props) {
  return React.createElement("div", undefined, React.createElement(MetalDetector.make, {}));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
