// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function GameCanvas(Props) {
  var width = Props.width;
  var height = Props.height;
  var canvasClassName = Props.canvasClassName;
  var canvasRef = Props.canvasRef;
  var onMouseMove = Props.onMouseMove;
  var onClick = Props.onClick;
  return React.createElement("canvas", {
              ref: canvasRef,
              className: "game-canvas " + canvasClassName,
              height: String(height),
              width: String(width),
              onClick: onClick,
              onMouseMove: onMouseMove
            });
}

var make = GameCanvas;

export {
  make ,
  
}
/* react Not a pure module */
