// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function GameCanvas(Props) {
  var width = Props.width;
  var height = Props.height;
  var canvasClassName = Props.canvasClassName;
  var canvasRef = Props.canvasRef;
  return React.createElement("canvas", {
              ref: canvasRef,
              className: "game-canvas " + canvasClassName,
              height: height,
              width: width
            });
}

var make = GameCanvas;

export {
  make ,
  
}
/* react Not a pure module */
