// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as GameCanvas from "./GameCanvas.bs.js";

function MetalDetector(Props) {
  var gameCanvasRef = React.useRef(null);
  React.useEffect(function () {
        
      });
  return React.createElement("div", undefined, React.createElement("h2", undefined, "metal detector game"), React.createElement(GameCanvas.make, {
                  width: "600",
                  height: "500",
                  canvasClassName: "metal-detector-canvas",
                  canvasRef: gameCanvasRef
                }));
}

var make = MetalDetector;

export {
  make ,
  
}
/* react Not a pure module */
